# Generated by Django 4.1 on 2022-10-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar_tabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tab', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Piano_tabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tab', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('photo', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('views', models.IntegerField(default=0, verbose_name='number')),
                ('guitar_tabs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guitar_tabs', to='tabs.guitar_tabs')),
                ('piano_tabs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piano_tabs', to='tabs.piano_tabs')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
