# Generated by Django 4.1 on 2022-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0002_alter_songs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
