# Generated by Django 4.1 on 2022-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0003_alter_songs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar_tabs',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='piano_tabs',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='guitar_tabs',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='piano_tabs',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='songs',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
    ]
