# Generated by Django 4.1 on 2022-10-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0004_guitar_tabs_price_piano_tabs_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitar_tabs',
            old_name='tab',
            new_name='tab_text',
        ),
        migrations.RenameField(
            model_name='piano_tabs',
            old_name='tab',
            new_name='tab_text',
        ),
    ]
