# Generated by Django 4.1 on 2022-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0006_alter_songs_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_tabs',
            name='tab_text',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='piano_tabs',
            name='tab_text',
            field=models.TextField(default=''),
        ),
    ]
