# Generated by Django 4.1 on 2022-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0008_alter_guitar_tabs_tab_text_alter_piano_tabs_tab_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_tabs',
            name='tab_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='piano_tabs',
            name='tab_text',
            field=models.TextField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
