# Generated by Django 4.1 on 2022-10-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0009_alter_guitar_tabs_tab_text_alter_piano_tabs_tab_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='piano_tabs',
        ),
        migrations.DeleteModel(
            name='Piano_tabs',
        ),
    ]
