# Generated by Django 4.1 on 2022-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0012_alter_guitar_tabs_options_remove_guitar_tabs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_tabs',
            name='tab_text',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
