# Generated by Django 4.1 on 2022-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0013_alter_guitar_tabs_tab_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_tabs',
            name='tab_text',
            field=models.TextField(blank=True),
        ),
    ]
