# Generated by Django 4.1 on 2022-10-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0015_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='users_id',
        ),
    ]
